config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end

  devise_for :users

  root to: 'job_offers#index'

  namespace :job_offers, path: 'jobs' do 
    resources :redirects, only: [:show]
    resources :previews, only: [:show], param: :token
    resources :summaries, only: [:show], param: :token
    resources :submissions, only: [:create, :destroy], param: :token
    resources :publications, only: [:create], param: :token
  end

  resources :jobs, except: [:destroy, :show], controller: 'job_offers', as: 'job_offers', param: :token
  resources :jobs, only: [:show], controller: 'job_offers', as: 'job_offers'
  resources :newsletter_subscriptions, only: [:create]

  get 'newsletter_subscriptions/:confirm_token/confirm', to: 'newsletter_subscriptions/confirmations#create', as: 'newsletter_subscription_confirmation'
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  include AASM
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  DEFAULT_REFRESH_TIME = 30.days
  FACET_SLUGS = %w(location experience)

  belongs_to :company
  has_many :sites, dependent: :destroy 
  has_many :locations, through: :sites

  scope :active, -> { where("state != 'created' AND state != 'closed'") }

  has_one_attached :logo

  accepts_nested_attributes_for :company

  validates :title, :locations, :salary, :apply_link, :email, presence: true
  validate :emails_have_correct_format

  before_create :generate_token

  aasm column: 'state' do
    state :created, initial: true
    state :submitted
    state :published
    state :closed
    state :expired

    event :submit do
      transitions from: [:created, :expired], to: :submitted, success: -> { JobOfferSubmitter.new(self).call }
    end

    event :publish  do
      transitions from: [:created, :submitted, :closed, :expired], to: :published, success: -> { JobOfferPublisher.new(self).call } 
    end

    event :reject do
      transitions from: :submitted, to: :created, success: -> { update(submitted_at: nil) } 
    end

    event :close do
      transitions to: :closed
    end

    event :refresh do
      transitions from: :published, to: :published, success: -> { JobOfferRefresher.new(self).call }
    end
  end

  settings do 
    mappings dynamic: false do
      indexes :location, type: :nested do
        indexes :slug, type: :keyword
        indexes :name, type: :keyword
      end

      indexes :experience, type: :nested do
        indexes :slug, type: :keyword
        indexes :name, type: :keyword
      end

      indexes :state, type: :keyword
      indexes :published_at, type: :date
    end
  end

  def as_indexed_json(options = {})
    {
      "location" => location_slugs,
      "experience" => experience,
      "state" => state,
      "published_at" => published_at
    }
  end

  def location_slugs
    locations.pluck(:name).map do |name| 
      slug = name == 'Zdalnie' ? 'remote' : name.parameterize
      {
        slug: slug,
        name: name
      }
    end
  end

  def experience
    exp = []

    exp << {slug: 'junior', name: 'Junior'} if title =~ /junior|młodszy/i
    exp << {slug: 'senior', name: 'Senior'} if title =~ /senior|starszy|lead|cto/i
    exp << {slug: 'mid', name: 'Mid'} if title =~ /Mid/i || exp.empty?

    exp
  end

  def city_names
    locations.reject{|location| location.name == 'Zdalnie'}.map(&:name).join(', ')
  end

  def city_names=(city_names)
    location_params = city_names.split(/\s*,\s*/).map do |city_name|
      {name: city_name}
    end

    self.locations = (
      locations.select{|location| location.name == 'Zdalnie'} + location_params.map{|location_params| Location.find_or_initialize_by(location_params)}
    ).uniq(&:name)
  end

  def emails
    email.to_s.split(',').map(&:strip)
  end

  def remote
    locations.select{|location| location.name == 'Zdalnie'}.count > 0 ? '1' : '0'
  end

  def remote=(value)
    if value == "1" 
      locations << Location.find_or_initialize_by(name: 'Zdalnie') unless locations.find{|location| location.name == 'Zdalnie'}
    elsif value == "0" && remote_location = Location.find_by(name: 'Zdalnie')
      locations.destroy(remote_location)
    end
  end

  def company_attributes=(attributes)
    self.company = Company.find_or_initialize_by(name: attributes[:name]) do |company|
      company.logo = attributes[:logo]
    end
  end

  def to_param
    [id, title.parameterize, company.name.parameterize].join('-')
  end

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless JobOffer.exists?(token: random_token)
    end
  end

  def refresh_time_in_days
    duration_parts = ActiveSupport::Duration.build(DEFAULT_REFRESH_TIME).parts
    duration_parts[:weeks].to_i * 7 + duration_parts[:days]
  end

  def logo_attached?
    logo.attached? || company.logo.attached?
  end

  private

  def emails_have_correct_format
    errors.add(:email, I18n.t('errors.messages.invalid')) if emails.any?{ |email| email !~ /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  end
end

app/controllers/job_offers/previews_controller.rb
class JobOffers::PreviewsController < ApplicationController
  def show
    @job_offer = JobOffer.find_by(token: params[:token]).decorate
  end
end

app/controllers/job_offers/publications_controller.rb
class JobOffers::PublicationsController < ApplicationController
  before_action :find_job_offer
  before_action :authorize_job_offer

  def create
    @job_offer.publish!

    redirect_back(fallback_location: root_path)
  end

  private

  def find_job_offer
    @job_offer = JobOffer.find_by(token: params[:token])
  end

  def authorize_job_offer
    authorize @job_offer
  end
end

app/controllers/job_offers/redirects_controller.rb
class JobOffers::RedirectsController < ApplicationController
  def show
    @job_offer = JobOffer.find(params[:id])

    RegisterApplyLinkClickJob.perform_later(@job_offer.id) if @job_offer.published?

    if @job_offer.apply_link =~ URI::MailTo::EMAIL_REGEXP
      redirect_to "mailto:#{@job_offer.apply_link}"
    else
      redirect_to @job_offer.apply_link
    end
  end
end

app/controllers/job_offers/submissions_controller.rb
class JobOffers::SubmissionsController < ApplicationController
  def create
    job_offer = JobOffer.find_by(token: params[:token])

    if current_user.admin?
      job_offer.publish!

      flash[:notice] = "Ogłoszenie zostało opublikowane."
    else
      job_offer.submit!

      flash[:notice] = "Ogłoszenie czeka na akceptację. Po akceptacji otrzymasz maila na adres #{job_offer.email}"
    end

    redirect_to root_path
  end

  def destroy
    @job_offer = JobOffer.find_by(token: params[:token])
    authorize @job_offer

    @job_offer.reject!
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/job_offers/summaries_controller.rb
class JobOffers::SummariesController < ApplicationController
  def show
    @job_offer = JobOffer.find_by(token: params[:token]).decorate
  end
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  helper_method :facet_slug_active?

  def index
    @job_offers, @filters = JobOfferFinder.new(search_params, current_user).call

    @job_offers = @job_offers.decorate
  end

  def show
    @job_offer = JobOffer.find(params[:id]).decorate

    flash[:notice] = 'Ogłoszenie jest już nieaktualne.' if @job_offer.closed?

    RegisterJobOfferVisitJob.perform_later(@job_offer.id) if @job_offer.published?
  end

  def new
    @job_offer = JobOffer.new
    @job_offer.build_company
  end

  def create
    @job_offer = JobOfferCreator.new(job_offer_params).call

    if @job_offer.valid?
      redirect_to job_offers_preview_path(@job_offer.token)
    else
      render :new
    end
  end

  def edit
    @job_offer = JobOffer.find_by(token: params[:token])
  end

  def update
    @job_offer = JobOffer.find_by(token: params[:token])

    if @job_offer.update(job_offer_params)
      redirect_to job_offers_preview_path(@job_offer.token)
    else
      render :edit
    end
  end

  private

  def search_params
    params.permit(location: [], experience: [])
  end

  def facet_slug_active?(facet_slug)
    search_params.values.flatten.include?(facet_slug)
  end

  def job_offer_params
    params.require(:job_offer).permit(:title, :city_names, :remote, :salary, :salary_type, :description, :apply_link, :logo, :email, company_attributes: [:name])
  end

end

app/views/job_offers/_filler.html.erb
<% (3 - @job_offers.count % 3).times do %>
  <div class="w-full sm:w-1/2 lg:w-1/3"></div>
<% end %>

app/views/job_offers/_filters_sidebar.html.erb
<div 
  data-controller="filters" 
  data-target="mobile.filtersContainer"
  class="<%= "hidden" unless cookies[:filters] == "on" %> md:block mb-6 xl:col-span-2 md:col-span-1">
  <div class="bg-white border border-gray-200 px-5 py-5">
    <div class="flex justify-between items-center">
      <p class="font-header text-xl font-medium mb-2">Filtry</p>
      <%= 
        link_to "Wyczyść", root_path, 
          class: "hidden text-red-600 font-semibold", 
          data: {target: "filters.clearLink"} 
        %>
  </div>

  <% @filters.each do |category_slug, facets| %>
    <p class="font-header text-lg font-medium mb-3"><%= I18n.t("facets.categories.#{category_slug}") %></p>
    <div class="category" id="<%= "#{category_slug}"%>">
      <% facets.each do |facet| %>
        <div class="flex justify-between mb-3 <%= "text-gray-400" if facet[:job_offers_count] == 0 %>">
          <label class="inline-flex items-center">
            <input type="checkbox" 
                   value="<%= facet[:slug] %>" 
                   <%= "checked" if facet_slug_active?(facet[:slug]) %> 
                   class="form-checkbox rounded-none w-5 h-5" 
                   <%= "disabled" if facet[:job_offers_count] == 0 %>
                   data-action="change->filters#update">
                   <span class="ml-3"><%= facet[:name] %></span>
          </label>
          <span><%= facet[:job_offers_count] %></span>
        </div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/job_offers/_job_offer.html.erb
<%= link_to job_offer do %>
  <div class="bg-white border border-gray-200 flex px-6 py-5 mb-6">
    <div class="w-20 h-20 md:w-16 md:h-16 lg:w-20 lg:h-20 mr-6 self-center flex items-center justify-center">
      <% if job_offer.logo.attached? %>
        <%= image_tag(job_offer.logo, class: "max-w-full max-h-full block") %>
      <% elsif job_offer.company.logo.attached? %>
        <%= image_tag(job_offer.company.logo, class: "max-w-full max-h-full block") %>
      <% end %>
    </div>
    <div class="flex-grow">
      <div class="flex flex-col sm:flex-row justify-between">
        <p><%= job_offer.company.name %></p>
        <p><%= job_offer.formatted_salary %> <span class="hidden sm:inline">(<%= job_offer.salary_type %>)</span></p>
      </div>
      <p class="text-2xl font-header font-medium my-2"><%= job_offer.title %></p>
      <%= job_offer.location_names %>
    </div>
  </div>
<% end %>

app/views/job_offers/_newsletter.html.erb
<%= form_with url: newsletter_subscriptions_path, class:"w-full sm:w-1/2 lg:w-1/3 px-4 mb-12" do |form| %>
  <div class="h-full flex flex-col border bg-red-100 p-6 justify-between">
    <div class="flex flex-col items-center text-center mb-8">
      <p class="text-2xl mb-6 font-bold">Przegląd ofert</p>
      <p class="mb-8">Zapisz się na cotygodniowy przegląd ofert wysyłany na maila.</p>
      <%= form.email_field :email, class: "border px-4 py-2 self-stretch bg-gray-100 focus:bg-white", placeholder: "Adres email" %>
    </div>
    <%= form.submit "Zapisz się", class: "bg-red-500 text-white font-bold text-xl py-3" %>
  </div>
<% end %>

app/views/job_offers/edit.html.erb
<div class="container m-auto max-w-3xl px-4 pt-8 pb-10">
  <h1 class="text-4xl font-bold text-red-800 font-serif mb-10 text-center">RubyJobs.pl</h1>
  <div class="flex justify-between">
    <div class="flex-1 text-center">
      <p class="border-b-4 border-red-600 text-red-600 font-bold pb-3 mb-3 text-xl">Krok 1</p>
      <p class="text-2xl text-gray-700">Dodaj<span class="hidden sm:inline"> ogłoszenie<span></p>
    </div>
    <div class="flex-1 text-center">
      <p class="border-b-4 text-red-600 font-bold pb-3 mb-3 text-xl">Krok 2</p>
      <p class="text-2xl text-gray-700">Podgląd<span class="hidden sm:inline"> ogłoszenia<span></p>
    </div>
    <div class="flex-1 text-center">
      <p class="border-b-4 text-red-600 font-bold pb-3 mb-3 text-xl">Krok 3</p>
      <p class="text-2xl text-gray-700 font-sans">Publikuj</p>
    </div>
  </div>
</div>

<div class="container mx-auto px-4 pb-10 max-w-3xl">
  <%= form_with model: @job_offer, url: job_offer_path(@job_offer.token), method: :patch, local: true do |form| %>
    <h2 class="text-2xl text-red-600 border-b pb-2 mb-5">Informacje o stanowisku</h2>

    <div class="mb-6">
      <%= form.label :title, "Nazwa stanowiska", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :title} %>
      <%= form.text_field :title, class: "#{'border-red-500' if @job_offer.errors[:title].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <p class="text-sm text-gray-500">Na przykład: Senior Ruby on Rails Developer.</p>
    </div>

    <div class="mb-6">
      <%= form.label :city_names, "Miasto", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :locations} %>
      <%= form.text_field :city_names, class: "#{'border-red-500' if @job_offer.errors[:locations].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <p class="text-sm text-gray-500">Na przykład: Warszawa, Białystok.</p>
      <div>
        <%= form.label :remote, class: "text-gray-700 block mt-2" do %>
          <%= form.check_box :remote, class: "mr-2 align-middle" %>
          <span class="">
            Praca zdalna?
          </span>
        <% end %>
      </div>
    </div>

    <div class="mb-6">
      <%= form.label :salary, "Zarobki", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :salary} %>
      <%= form.text_field :salary, class: "#{'border-red-500' if @job_offer.errors[:salary].present?} mr-4 border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <div class="relative inline-block">
        <%= form.select :salary_type, options_for_select(["B2B", "Umowa o pracę", "Umowa o dzieło"], @job_offer.salary_type), {}, class: "w-20 sm:w-48 px-2 py-2 bg-gray-100 border appearance-none" %>
        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
          <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
        </div>
      </div>
      <p class="text-sm text-gray-500">Widełki płacowe, np. 5000 - 7000.</p>
    </div>

    <div class="mb-6">
      <%= form.label :description, "Treść ogłoszenia", class: "block text-gray-700 mb-2 text-lg" %>
      <%= form.trix_editor :description, class: "border w-full px-6 py-5 bg-gray-100 focus:bg-white" %>
    </div>

    <div class="mb-6">
      <%= form.label :apply_link, "Link do aplikowania", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :apply_link} %>
      <%= form.text_field :apply_link, class: "#{'border-red-500' if @job_offer.errors[:apply_link].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <p class="text-sm text-gray-500">Np. https://nazwafirmy.pl/jobs/apply lub jobs@nazwafirmy.pl</p>
    </div>

    <h2 class="text-2xl text-red-600 border-b pb-2 mb-5">Informacje o firmie</h2>

    <%= form.fields_for :company do |company_fields| %>
      <div class="mb-6">
        <%= form.label :name, "Nazwa firmy", class: "block text-gray-700 mb-2 text-lg" %>
        <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :'company.name'} %>
        <%= company_fields.text_field :name, class: "#{'border-red-500' if @job_offer.errors[:apply_link].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      </div>
    <% end %>

    <% if @job_offer.logo_attached? %>
      <div class="mb-6">
        <p class="block text-gray-700 mb-2 text-lg">Aktualne logo </p>
        <% if @job_offer.logo.attached? %>
          <%= image_tag(@job_offer.logo, class: 'w-12 mr-4') %>
        <% elsif @job_offer.company.logo.attached? %>
          <%= image_tag(@job_offer.company.logo, class: 'w-12 mr-4') %>
        <% end %>
      </div>
    <% end %>

    <div class="mb-6">
      <%= form.label :logo, "#{@job_offer.logo_attached? ? 'Nowe logo' : 'Logo'}", class: "block text-gray-700 mb-2 text-lg" %>
        <%= form.file_field :logo, class: "border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
    </div>

    <div class="mb-6">
      <%= form.label :email, "Email", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :email} %>
      <%= form.text_field :email, class: "#{'border-red-500' if @job_offer.errors[:email].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
    </div>

    <div class="flex justify-between border-t pt-8">
      <button class="text-red-600 py-4 text-xl font-bold"></button>
      <%= form.submit "Dalej", class: "bg-red-600 text-white px-12 py-4 text-xl font-bold" %>
    </div>
  <% end %>
</div>

app/views/job_offers/index.html.erb
<div class="bg-gray-100 py-10" data-controller="mobile">
  <div class="hidden md:hidden fixed bottom-0 w-full " data-target="mobile.showJobOffers">
    <a class="block bg-red-500 mx-5 my-2 text-white text-center py-6 font-semibold text-lg"
       data-action="click->mobile#hide" >
      Pokaż ogłoszenia (<%= @job_offers.length %>)
    </a>
  </div>

  <div class="container m-auto md:grid xl:grid-cols-7 md:grid-cols-3 md:gap-8 px-5">
    <%= render 'filters_sidebar' %>

    <div 
       data-target="mobile.mainContainer" 
       class="<%= "hidden" if cookies[:filters] == "on" %> md:block xl:col-span-5 md:col-span-2">
       <a class="block md:hidden mb-4 inline-flex items-center"
         data-action="click->mobile#show">
         <svg class="fill-current w-6 h-6 mr-2" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><defs><style>.cls-1{fill:none;}</style></defs><title/><g data-name="Layer 2" id="Layer_2"><path d="M28,9H11a1,1,0,0,1,0-2H28a1,1,0,0,1,0,2Z"/><path d="M7,9H4A1,1,0,0,1,4,7H7A1,1,0,0,1,7,9Z"/><path d="M21,17H4a1,1,0,0,1,0-2H21a1,1,0,0,1,0,2Z"/><path d="M11,25H4a1,1,0,0,1,0-2h7a1,1,0,0,1,0,2Z"/><path d="M9,11a3,3,0,1,1,3-3A3,3,0,0,1,9,11ZM9,7a1,1,0,1,0,1,1A1,1,0,0,0,9,7Z"/><path d="M23,19a3,3,0,1,1,3-3A3,3,0,0,1,23,19Zm0-4a1,1,0,1,0,1,1A1,1,0,0,0,23,15Z"/><path d="M13,27a3,3,0,1,1,3-3A3,3,0,0,1,13,27Zm0-4a1,1,0,1,0,1,1A1,1,0,0,0,13,23Z"/><path d="M28,17H25a1,1,0,0,1,0-2h3a1,1,0,0,1,0,2Z"/><path d="M28,25H15a1,1,0,0,1,0-2H28a1,1,0,0,1,0,2Z"/></g><g id="frame"><rect class="cls-1" height="32" width="32"/></g></svg>
           <span class="text-lg">Filtry</span>
      </a>
      <%= render @job_offers %>
    </div>
  </div>
</div>

app/views/job_offers/new.html.erb
<div class="container m-auto max-w-3xl px-4 pt-8 pb-10">
  <h1 class="text-4xl font-bold text-red-800 font-serif mb-10 text-center">RubyJobs.pl</h1>
  <div class="flex justify-between">
    <div class="flex-1 text-center">
      <p class="border-b-4 border-red-600 text-red-600 font-bold pb-3 mb-3 text-xl">Krok 1</p>
      <p class="text-2xl text-gray-700">Dodaj<span class="hidden sm:inline"> ogłoszenie<span></p>
    </div>
    <div class="flex-1 text-center">
      <p class="border-b-4 text-red-600 font-bold pb-3 mb-3 text-xl">Krok 2</p>
      <p class="text-2xl text-gray-700">Podgląd<span class="hidden sm:inline"> ogłoszenia<span></p>
    </div>
    <div class="flex-1 text-center">
      <p class="border-b-4 text-red-600 font-bold pb-3 mb-3 text-xl">Krok 3</p>
      <p class="text-2xl text-gray-700 font-sans">Publikuj</p>
    </div>
  </div>
</div>

<div class="container mx-auto px-4 pb-10 max-w-3xl">
  <%= form_with model: @job_offer, local: true do |form| %>
    <h2 class="text-2xl text-red-600 border-b pb-2 mb-5">Informacje o stanowisku</h2>

    <div class="mb-6">
      <%= form.label :title, "Nazwa stanowiska", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :title} %>
      <%= form.text_field :title, class: "#{'border-red-500' if @job_offer.errors[:title].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <p class="text-sm text-gray-500">Na przykład: Senior Ruby on Rails Developer.</p>
    </div>

    <div class="mb-6">
      <%= form.label :city_names, "Miasto", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :locations} %>
      <%= form.text_field :city_names, class: "#{'border-red-500' if @job_offer.errors[:locations].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <p class="text-sm text-gray-500">Na przykład: Warszawa, Białystok.</p>
      <div>
        <%= form.label :remote, class: "text-gray-700 block mt-2" do %>
          <%= form.check_box :remote, class: "mr-2 align-middle" %>
          <span class="">
            Praca zdalna?
          </span>
        <% end %>
      </div>
    </div>

    <div class="mb-6">
      <%= form.label :salary, "Zarobki", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :salary} %>
      <%= form.text_field :salary, class: "#{'border-red-500' if @job_offer.errors[:salary].present?} mr-4 border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <div class="relative inline-block">
        <%= form.select :salary_type, options_for_select(["B2B", "Umowa o pracę", "Umowa o dzieło"], @job_offer.salary_type), {}, class: "w-20 sm:w-48 px-2 py-2 bg-gray-100 border appearance-none" %>
        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
          <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
        </div>
      </div>
      <p class="text-sm text-gray-500">Widełki płacowe, np. 5000 - 7000.</p>
    </div>

    <div class="mb-6">
      <%= form.label :description, "Treść ogłoszenia", class: "block text-gray-700 mb-2 text-lg" %>
      <%= form.trix_editor :description, class: "border w-full px-6 py-5 bg-gray-100 focus:bg-white" %>
    </div>

    <div class="mb-6">
      <%= form.label :apply_link, "Link do aplikowania", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :apply_link} %>
      <%= form.text_field :apply_link, class: "#{'border-red-500' if @job_offer.errors[:apply_link].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      <p class="text-sm text-gray-500">Np. https://nazwafirmy.pl/jobs/apply lub jobs@nazwafirmy.pl</p>
    </div>

    <h2 class="text-2xl text-red-600 border-b pb-2 mb-5">Informacje o firmie</h2>

    <%= form.fields_for :company do |company_fields| %>
      <div class="mb-6">
        <%= form.label :name, "Nazwa firmy", class: "block text-gray-700 mb-2 text-lg" %>
        <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :'company.name'} %>
        <%= company_fields.text_field :name, class: "#{'border-red-500' if @job_offer.errors[:apply_link].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
      </div>
    <% end %>

    <div class="mb-6">
      <%= form.label :logo, "Logo", class: "block text-gray-700 mb-2 text-lg" %>
      <%= form.file_field :logo, class: "border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
    </div>

    <div class="mb-6">
      <%= form.label :email, "Email", class: "block text-gray-700 mb-2 text-lg" %>
      <%= render partial: 'shared/error', locals: {resource: @job_offer, attribute_name: :email} %>
      <%= form.text_field :email, class: "#{'border-red-500' if @job_offer.errors[:email].present?} w-full border px-2 py-2 mb-1 bg-gray-100 focus:bg-white" %>
    </div>

    <div class="flex justify-between border-t pt-8">
      <button class="text-red-600 py-4 text-xl font-bold"></button>
      <%= form.submit "Dalej", class: "bg-red-600 text-white px-12 py-4 text-xl font-bold" %>
    </div>
  <% end %>
</div>

app/views/job_offers/show.html.erb
<div class="border-b">
  <div class="container mx-auto mb-8">
    <div class="pt-8 pb-8 px-5 max-w-4xl">
      <div class="border-b pb-5">
        <p class="text-gray-800 text-xl mb-2"><%= @job_offer.company.name %></p>
        <p class="text-2xl font-bold"><%= @job_offer.title %></p>
        <p class="text-gray-800 mb-2"><%= @job_offer.location_names %></p>
        <p class="text-gray-800"><%= @job_offer.salary %> (<%= @job_offer.salary_type %>)</p>
      </div>
      <div class="mt-5 leading-relaxed text-gray-800 mb-6">
        <div class="trix-content" ng-bind-html="$ctrl.offer.body">
          <%= @job_offer.description.html_safe %>
        </div>
      </div>
      <%= link_to "Aplikuj teraz", job_offers_redirect_path(@job_offer.id), class: "bg-red-600 text-white font-bold px-6 py-4 inline-block text-lg" %> 
    </div>
  </div>
</div>