config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end

  devise_for :users

  root to: 'job_offers#index'

  namespace :job_offers, path: 'jobs' do 
    resources :redirects, only: [:show]
    resources :previews, only: [:show], param: :token
    resources :summaries, only: [:show], param: :token
    resources :submissions, only: [:create, :destroy], param: :token
    resources :publications, only: [:create], param: :token
  end

  resources :jobs, except: [:destroy, :show], controller: 'job_offers', as: 'job_offers', param: :token
  resources :jobs, only: [:show], controller: 'job_offers', as: 'job_offers'
  resources :newsletter_subscriptions, only: [:create]

  get 'newsletter_subscriptions/:confirm_token/confirm', to: 'newsletter_subscriptions/confirmations#create', as: 'newsletter_subscription_confirmation'
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div data-controller="flash-messages" data-target="flash-messages.container" class="bg-red-500 p-4 text-center text-white font-bold relative">
    <%= flash[:notice] %>
    <span data-action="click->flash-messages#close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-white" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Zamknij</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

<% if flash[:alert] %>
  <div data-controller="flash-messages" data-target="flash-messages.container" class="bg-red-500 p-4 text-center text-white font-bold relative">
    <%= flash[:notice] %>
    <span data-action="click->flash-messages#close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-white" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Zamknij</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="py-3">
  <div class="container m-auto px-5 flex justify-between">
    <div class="hidden sm:block">
      <%= link_to "RubyJobs.pl", root_path, class: "block text-red-800 text-xl font-bold font-header" %>
      <p class="mt-2">Ogłoszenia pracy dla programistów Rubiego.</p>
    </div>
    <div>
      <p>Kontakt:</p>
      <%= link_to "marcin@rubyjobs.pl", "mailto:marcin@rubyjobs.pl", class: "block mt-2 text-red-800" %>
    </div>
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-141917378-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-141917378-1');
  </script>
<% end %>

app/views/layouts/_header.html.erb
<div data-controller="mobile-menu" >
  <div class="border-b border-gray-200 py-3">
    <div class="container m-auto px-5">
      <div class="flex justify-between items-center">
        <%= link_to "RubyJobs.pl", root_path, class: "text-red-800 text-2xl font-bold font-header" %>
        <div class="hidden md:flex items-center">
          <% if user_signed_in? %>
            <%= link_to('Wyloguj się', destroy_user_session_path, method: :delete) %>        
          <% else %>
            <%= link_to('Zaloguj się', new_user_session_path) %>  
          <% end %>
          <%= link_to "Dodaj ogłoszenie", new_job_offer_path, class: "border-2 border-red-600 bg-red-100 px-3 py-2 block ml-4 hidden sm:block" %>
        </div>
        <div data-action="click->mobile-menu#toggle" class="md:hidden text-gray-700 flex-grow flex flex-row-reverse">
          <svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </div>
      </div>
    </div>
  </div>
  <div data-target="mobile-menu.menu" class="hidden md:hidden border-b border-gray-200 container m-auto py-5 px-5 text-lg leading-relaxed">
    <div class="flex flex-col">
      <% if user_signed_in? %>
        <%= link_to('Wyloguj się', destroy_user_session_path, method: :delete) %>        
      <% else %>
        <%= link_to('Zaloguj się', new_user_session_path) %>  
      <% end %>
      <%= link_to "Dodaj ogłoszenie", new_job_offer_path, class: "text-red-600" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/google_analytics' %>
    <title>RubyJobs.pl - Ogłoszenia pracy dla programistów Rubiego</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="<%= image_path("og_logo.png") %>" />
    <%= favicon_link_tag('favicon.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="font-body">
    <%= render "layouts/flash_messages" %>
    <%= render "layouts/header" %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>